config/routes.rb
Rails.application.routes.draw do
  Rails.application.routes.draw do
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
    #get controller
    get "about", to: "about#index"

    get "password", to: "password#edit", as: :edit_password
    patch "password", to: "password#update"

    get "sign_up", to: "registration#new"
    post "sign_up", to: "registration#create"

    get "sign_in", to: "sessions#new"
    post "sign_in", to: "sessions#create"

    get "password/reset", to: "password_resets#new"
    post "password/reset", to: "password_resets#create"

    get "password/reset/edit", to: "password_resets#edit"
    patch "password/reset/edit", to: "password_resets#update"

    delete "logout", to: "sessions#destroy"
    root to: "main#index"
    # Defines the root path route ("/")
    # root "articles#index"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  VALID_EMAIL_REGEX= /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i

  validates :email , presence: true,uniqueness:{case_sensetive:false},
            format:{with:VALID_EMAIL_REGEX,multiline:true}
  # validates :email, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :set_current_user

  def set_current_user
    if session[:user_id]
      Current.user = User.find_by(id: session[:user_id])
    end
  end

  def require_user_logged_in
    redirect_to sign_in_path, notice: "Please login to process the request" if Current.user.nil?
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index


  end
end

app/controllers/password_controller.rb
class PasswordController < ApplicationController
  before_action :require_user_logged_in

  def edit

  end

  def update
    if Current.user.update(params_password)
      redirect_to root_path, notice: "Password Updated Successfully"
    else
      render :edit
    end

  end

  private
  def params_password
    params.require(:user).permit(:password,:password_confirmation)
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new

  end

  def create
    @user=User.find_by(email: params[:email])

    if @user.present?
      #send email
      PasswordMailer.with(user:@user).reset.deliver_later
    end

    redirect_to root_path, notice: "If an account with that email was found , we Have sent a link to reset your password"
  end

  def edit
    @user = User.find_signed!(params[:token],purpose: "password_reset")
  rescue ActiveSupport::MessageVerifier::InvalidSignature
    redirect_to sign_in_path, notice: "Your link has been expired"
  end

  def update
    @user = User.find_signed!(params[:token],purpose: "password_reset")
    if @user.update(password_params)
      redirect_to sign_in_path, notice: "Password updated Successfully"
    else
      puts("hello")
      render :edit
    end
  end

  private
  def password_params
    params.require(:user).permit(:password,:password_confirmation)
  end

end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user=User.new(user_params)
    if @user.save
      session[:user_id]=@user.id
      redirect_to root_path,notice: "Account created Successfully"
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:email,:password,:password_confirmation)
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(email: params[:email])

    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Logged In Successfully"
    else
      flash[:notice] = "Invalid email of password."
      render :new
    end

  end

  def destroy
    session[:user_id]= nil
    redirect_to root_path, notice: "Logged out successfully"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1> hello</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Porter</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
<%= render partial: "shared/navbar" %>
<div class="container">
  <%=render partial: "shared/flash" %>
  <%= yield %>
</div>
</body>
</html>

app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center">
<h1> welcome to schedule tweets</h1>

</div>

app/views/password/edit.html.erb
<h1> Edit Password</h1>

<%= form_with model: Current.user, url: edit_password_path, data: { turbo: false },local: true do |form| %>

  <% if form.object.errors.any? %>
    <div class="alert alert-danger">
      <% form.object.errors.full_messages.each do |message| %>
        <div><%= message %></div>
      <%end %>
    </div>
  <%end %>

  <div class="mb-3">
    <%=form.label :password %>
    <%= form.password_field :password, class:"form-control",placeholder: "password" %>
  </div>
  <div class="mb-3">
    <%=form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class:"form-control", placeholder: "password" %>
  </div>

  <div>
    <%= form.submit "Get Started", class:"btn btn-primary"%>
  </div>
<%end %>

app/views/password_resets/edit.html.erb
<h1>Reset your password?</h1>

<%= form_with model: @user,url: password_reset_edit_path(token:params[:token]) do |form| %>

  <% if form.object.errors.any? %>
    <div class="alert alert-danger">
      <% form.object.errors.full_messages.each do |message| %>
        <div><%= message %></div>
      <%end %>
    </div>
    <%end %>

  <div class="mb-3">
    <%=form.label :password %>
    <%= form.password_field :password, class:"form-control",placeholder: "password" %>
  </div>
  <div class="mb-3">
    <%=form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class:"form-control", placeholder: "password" %>
  </div>

  <div>
    <%= form.submit "Reset", class:"btn btn-primary"%>
  </div>

<%end %>

app/views/password_resets/new.html.erb
<h1>Forgot password?</h1>

<%= form_with url: "/password/reset" do |form| %>
  <div class="mb-3">
    <%=form.label :email %>
    <%= form.text_field :email, class:"form-control", placeholder: "star@gmail.com" %>
  </div>

  <div>
    <%= form.submit "Reset Password", class:"btn btn-primary"%>
  </div>

<%end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
<div class="alert alert-primary" role="alert">
<%= flash[:notice] %>
</div>
<% end%>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%=link_to "Navbar", root_path , class: "navbar-brand"  %>
<!--    <a class="navbar-brand" href="/">Welcome to Facebook</a>-->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%=link_to "Home", root_path,class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%=link_to "About", about_path, class: "nav-link" %>
        </li>
      </ul>
    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
      <% if Current.user %>
        <li class="nav-item">
          <%=link_to Current.user.email,edit_password_path, class: "nav-link" %>
        <li class="nav-item">
        <%= button_to "logout", logout_path , method: :delete,class: "btn btn-outline-secondary" %>
        </li>
      <%else %>
        <li class="nav-item">
        <%=link_to "Login",sign_in_path,class: "nav-link" %>
        </li>
        <li class="nav-item">
        <%=link_to "Sign up",sign_up_path, class: "nav-link" %>
        </li>
      <%end %>

    </ul>


<!--      <div class="navbar-nav">-->

<!--        <a class="nav-link active" aria-current="page" href="/">Home</a>-->

<!--        <a class="nav-link" href="/about">About</a>-->
<!--        <a class="nav-link" href="#">Pricing</a>-->
<!--        <a class="nav-link disabled">Disabled</a>-->
<!--      </div>-->
    </div>
  </div>
</nav>